FROM arm32v7/ubuntu:latest

MAINTAINER cade <cade.call@mediciventures.com>

EXPOSE $RPCPORT

EXPOSE $PORT

RUN useradd -ms /bin/bash meowcoin

RUN mkdir /etc/meowcoin

RUN mkdir /var/lib/meowcoin

RUN chown meowcoin:meowcoin /etc/meowcoin /var/lib/meowcoin

WORKDIR /home/meowcoin

COPY --chown=meowcoin:meowcoin linux64/* ./run.sh /home/meowcoin/

USER meowcoin

CMD ["/home/meowcoin/run.sh"]
